name: Build ImmortalWrt-22.03 for N1

on:
  workflow_dispatch:
   inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
  schedule:
    - cron: "0 0 1,16 * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-22.03
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Free up space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null
        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/nantayo/My-Pkg/master/2203) > /dev/null

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update & Install feeds
      run: |
        chmod +x diy.sh
        cd openwrt
        ./scripts/feeds update -a
        $GITHUB_WORKSPACE/diy.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load N1 custom config
      run: |
        rm -rf openwrt/files openwrt/.config
        mv armsr/armv8/files armsr/armv8/.config openwrt/

  

    - name: Package armsr as openwrt
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/armsr/armv8/*rootfs.tar.gz
        KERNEL_REPO_URL: breakingbadboy/OpenWrt        
        KERNEL_VERSION_NAME: 5.10.y
        PACKAGE_SOC: diy
        GZIP_IMGS: .xz
        SCRIPT_DIY_PATH: armsr/armv8/mk_s905d_n1.sh
        WHOAMI: mengmengniao
        SW_FLOWOFFLOAD: 0
        SFE_FLOW: 0

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ImmortalWrt-22.03_${{ env.PACKAGED_OUTPUTDATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*.img.xz
        body: |
          基于 ImmortalWrt 22.03 编译
          * 基本信息
          IP: 192.168.11.2
          账户: root
          密码: password

  